### ISSUE TITLE
بدون توضیحات و یا آموزش متنی داخل پیج گیت من رو تحریک نمیکنه که نصبش کنم 

### ISSUE THREAD

**Issue by PersiaNDreameR** [TaraRostami/TXray#1]
.نبودن داکیومنت و آموزش تو تیوب باعث شده دیده نشه همینطور پوان و اینکه چه توفیقی نسبت به پنل رایج داره & ... و ... ممنون میشم ی آموزش خودتون تهیه کنید یا دوستان تولید محتوا کننده ‌و لینکش رو بزارید داخل پیج ریپو گیت هاب کار . ممنون بانو

**Comment by TaraRostami** [comment]
درود بر شما
به زودی آموزش نحوه استفاده از اسکریپت قرار خواهد گرفت
سپاس از همراهیتون
